seqsense/urg_stamped

- include/first_order_filter.h
- include/scip2/connection.h
- include/scip2/decode.h
- include/scip2/logger.h
- include/scip2/protocol.h
- include/scip2/response.h
- include/scip2/response/abstract.h
- include/scip2/response/parameters.h
- include/scip2/response/quit.h
- include/scip2/response/stream.h
- include/scip2/response/time_sync.h
- include/scip2/walltime.h
- include/timestamp_moving_average.h
- include/timestamp_outlier_remover.h
- src/scip2/logger.cpp
- src/urg_stamped.cpp
- test/src/test_decode.cpp
- test/src/test_first_order_filter.cpp
- test/src/test_timestamp_moving_average.cpp
- test/src/test_timestamp_outlier_remover.cpp
- test/src/test_walltime.cpp
Apply `PointerAlignment: Left`
> Format pointer alignment

- .github/workflows/bloom-release.yml
- .github/workflows/release-candidate.yml
Creating an issue with title of `Release 0.0.0` makes a release PR containing changelog update and version bump.
Merging the release PR runs bloom-release jobs.
> Automate bloom release

- CMakeLists.txt
- include/device_time_origin.h
- include/scip2/walltime.h
- src/urg_stamped.cpp
- test/src/test_device_time_origin.cpp
> Add check for device timestamp jump to node

- .github/workflows/bloom-release.yml
To show the latest version on GitHub repository page.
> Create GitHub Release after bloom release

- include/scip2/response.h
- include/scip2/response/reboot.h
- src/urg_stamped.cpp
> Reboot lidar when it is in abnormal state

- .travis.yml
for https://github.com/seqsense/urg_stamped/pull/74#issuecomment-671745964
> Download gh-pr-comment binary instead of using pip

- .travis.yml
- .travis/Dockerfile
forgot to replace in https://github.com/seqsense/urg_stamped/pull/75
> Use downloaded gh-pr-comment binary in docker container

- .travis/prerelease_test.sh
> Remove travis_retry from prerelease_test.sh

- CHANGELOG.rst
- package.xml
> Release 0.0.9

- CHANGELOG.rst
- package.xml
> Release 0.0.10

- src/urg_stamped.cpp
https://github.com/seqsense/urg_stamped/issues/101
> Send QT command twice to avoid being ignored

- CHANGELOG.rst
- package.xml
> Release 0.0.11

- CHANGELOG.rst
- package.xml
> Release 0.0.12

- CHANGELOG.rst
- package.xml
> Release 0.0.13

- include/urg_stamped/ros_logger.h
- src/ros_logger.cpp
- src/urg_stamped.cpp
- src/urg_stamped_node.cpp
- Output sensor information on start
- Make sensor identifiable when multiple sensors are connected
> Improve log outputs for multi-sensor configuration

- CHANGELOG.rst
- package.xml
> Release 0.0.14

- .github/workflows/bloom-release.yml
https://github.com/seqsense/sq-alpine-ros/pull/194
> Unuse actions/create-release

- src/urg_stamped.cpp
Restart the node if continuously errored
> Detect future timestamp as error

- .github/prerelease_test.sh
- .github/workflows/bloom-release.yml
- .github/workflows/prerelease.yaml
- .github/workflows/test.yaml
> Drop Melodic support

- .github/workflows/release-candidate.yml
- .github/workflows/test.yaml
Update actions and replace deprecated repo-sync/pull-request action by gh command
> Update CI actions
